butler_controller:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  Rev52_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev52
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Rev54_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev54
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Rev56_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev56
    pid: {p: 100.0, i: 0.01, d: 10.0}
